### ISSUE TITLE
switchNetwork stopped working

### ISSUE THREAD

**Issue by budowski** [ChainSafe/dappeteer#81] opened 2022-01-13 17:58 UTC
**Describe the bug**
switchNetwork no longer works:
* If MM version < 1.8.0 => fails on `waiting for selector '.popover-header__button' failed`
* If MM version >= 1.8.0 => [this line](https://github.com/ChainSafe/dappeteer/blob/master/src/metamask/switchNetwork.ts#L14) fails - basically `innerText` is empty in run-time for some reason. Using `textContent` instead works.

**To Reproduce**
Setup MM and call `switchNetwork` method.

**System:**
- OS: MacOS
- OS version: 12.1
- NodeJs version: 14.18.2
- dAppeteer version: 2.4.0
- testing framework: jest
- testing framework version: 26.6.0.

**Comment by irubido** [comment] 2022-01-14 16:10
I've tested it on both old project and one from scratch, both time `switchNetwork` worked as intended. 
Could you provide more info about your project or testing environment? 
When you say it no longer works, has it worked before for you, what is different now?

**Comment by budowski** [comment] 2022-01-14 16:13
Yes, it used to work, now stopped working after upgrading from 2.3.0 to 2.4.0 - 
For MM<1.8.0, shows the `waiting for selector` error, for MM>=1.8.0, doesn't switch the network.

**Comment by budowski** [comment] 2022-01-14 16:13
Yes, it used to work, now stopped working after upgrading from 2.3.0 to 2.4.0 - 
For MM<1.8.0, shows the `waiting for selector` error, for MM>=1.8.0, doesn't switch the network.

**Comment by bayological** [comment] 2022-01-14 20:48
I'm having the same issue.

- Metamask version - 10.1.1
- Dappeteer version - 2.2.0
Error message: 'waiting for selector `.network-dropdown-content--link` failed: timeout 30000ms exceeded'

**Comment by dennis-gonzales** [comment] 2022-02-12 03:51
> Yes, it used to work, now stopped working after upgrading from 2.3.0 to 2.4.0 - For MM<1.8.0, shows the `waiting for selector` error, for MM>=1.8.0, doesn't switch the network. (it does still work when I use the 2.3.0 version)
> 
> Testing env - this happens before I load any website, as part of initial setup, so other than the details I included in the original ticket (OS/NodeJS/etc. versions) - what else can I send here?

I have experienced the same issue.
as mention in the comment: `2.4.0 - doesn't work`, `2.3.0 - works`

Was able to fix the issue by downgrading. not the best fix, but that's the one option that works for me.

**Comment by BeroBurny** [comment] 2022-06-23 10:29
should be fixed in 3.0.0-rc.0

**Closed by BeroBurny** 2022-06-23 10:29 UTC
Labels: bug
